package com.epam.learn.service;

import com.epam.learn.page.yopmail.YopmailHomePage;
import org.openqa.selenium.WebDriver;

public class YopmailService {

  private WebDriver driver;

  public YopmailService(WebDriver driver) {
    this.driver = driver;
  }

  public void copyAutoGeneratedEmailAddress() {
    new YopmailHomePage(driver)
        .openPage()
        .generateNewEmailAddress()
        .copyEmailAddress();
  }

  public double getEstimatedCostFromGoogleCloudMessage() {
    return new YopmailHomePage(driver)
        .openPage()
        .goToEmailInboxPage()
        .getGoogleCloudEstimateMessage()
        .getTotalEstimatedCost();
  }
}
