package com.epam.learn.test;

import com.epam.learn.model.ComputeEngine;
import com.epam.learn.page.googlecloud.GoogleCloudPricingCalculatorEstimatePage;
import com.epam.learn.page.googlecloud.GoogleCloudPricingCalculatorPage;
import com.epam.learn.service.ComputeEngineCreator;
import org.testng.Assert;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

public class HardcoreTest extends CommonConditions {

  private GoogleCloudPricingCalculatorPage calculatorPage;
  private GoogleCloudPricingCalculatorEstimatePage estimatePage;
  private ComputeEngine computeEngine;
  private double costFromPricingCalculatorEstimatePage;
  private double costReceivedByEmail;

  @BeforeClass(description = "Hardcore scenario")
  public void testGoogleCloudPricingCalculator() {
    computeEngine = ComputeEngineCreator.withDataFromProperty();
    calculatorPage = calculatorService
        .getPricingCalculatorPageFromFirstPositionInSearchResults();
    estimatePage = calculatorService
        .addComputeEngineToEstimate(calculatorPage, computeEngine);
    costFromPricingCalculatorEstimatePage = estimatePage
        .getTotalEstimatedCost();
    tabManager.openNewTab();
    tabManager.switchToTab(1);
    yopmailService
        .copyAutoGeneratedEmailAddress();
    tabManager.switchToTab(0);
    calculatorService
        .sendEmailWithEstimatedCost(estimatePage);
    tabManager.switchToTab(1);
    costReceivedByEmail = yopmailService
        .getEstimatedCostFromGoogleCloudMessage();
  }

  @Test(description = "Check received by email total estimated cost")
  public void shouldGetTheSameCostAsOnCalculatorPage() {
    Assert.assertEquals(costReceivedByEmail, costFromPricingCalculatorEstimatePage,
        "total estimated cost received by email is different from the price calculator page");
  }
}
